# Generated by Django 2.2.4 on 2019-09-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='available_date',
            field=models.DateField(),
        ),
    ]
