# Generated by Django 2.2.4 on 2019-09-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20190923_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='image',
            field=models.ImageField(upload_to='hotels'),
        ),
    ]
